FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG RADARR_VERSION='5.12.2.9335'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    XDG_CONFIG_HOME='/config/xdg' \
    RADARR_VERSION="${RADARR_VERSION}"
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      gcompat \
      icu \
      mediainfo \
      libintl \
      sqlite-libs \
    && \
    curl -SsL https://github.com/Radarr/Radarr/releases/download/v${RADARR_VERSION}/Radarr.master.${RADARR_VERSION}.linux-musl-core-x64.tar.gz -o /tmp/radarr.tar.gz && \
    tar xzf /tmp/radarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Radarr && \
    find /opt/Radarr -type d -exec chmod 0755 {} \; && \
    find /opt/Radarr -type f -exec chmod 0644 {} \; && \
    chmod 0755 \
      /opt/Radarr/Radarr \
      /opt/Radarr/ffprobe \
      /opt/Radarr/createdump \
    && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config"]

### Expose ports
Expose 7878

