---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radarr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: radarr
    spec:
      containers:
        - name: radarr
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8686
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /downloads
              name: radarr-downloads
            - mountPath: /movies
              name: radarr-movies
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
      volumes:
        - name: radarr-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: radarr-downloads
          {{- if eq .Values.persistence.downloads.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads-pvc
          {{- else if eq .Values.persistence.downloads.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.downloads.nfs.server }}
            path: {{ .Values.persistence.downloads.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: radarr-movies
          {{- if eq .Values.persistence.movies.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-movies-pvc
          {{- else if eq .Values.persistence.movies.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.movies.nfs.server }}
            path: {{ .Values.persistence.movies.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
